server:
  port: 8765
spring:
  application:
    name: d-service

eureka:
  client:
    # 자신을 서비스로 등록하지 않음 (유레카 서버의 일반적인 설정)
    register-with-eureka: false
    # 레지스트리 정보를 가져오지 않음 (유레카 서버의 일반적인 설정)
    fetch-registry: false
    # 중요: 자신의 포트를 포함한 defaultZone 명시
    service-url:
      defaultZone: http://localhost:8765/eureka/
